// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMgR9Ar2661NUAfvIif5RMKA12FXnhlI',
    appId: '1:159757857452:web:918cb8cef9884a52a2a509',
    messagingSenderId: '159757857452',
    projectId: 'vnjob-1279d',
    authDomain: 'vnjob-1279d.firebaseapp.com',
    storageBucket: 'vnjob-1279d.appspot.com',
    measurementId: 'G-1NH8JHDHE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_tyDpmItiRHHvs8sYUOWCyd1Gg7MzdY',
    appId: '1:159757857452:android:9a73b9bc712f3f5fa2a509',
    messagingSenderId: '159757857452',
    projectId: 'vnjob-1279d',
    storageBucket: 'vnjob-1279d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiU5AfNHh3lP2mf2LlH0sJRh7EEneGgeQ',
    appId: '1:159757857452:ios:4976d55bbc2a6098a2a509',
    messagingSenderId: '159757857452',
    projectId: 'vnjob-1279d',
    storageBucket: 'vnjob-1279d.appspot.com',
    iosBundleId: 'com.example.myjobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiU5AfNHh3lP2mf2LlH0sJRh7EEneGgeQ',
    appId: '1:159757857452:ios:6ccdb793dc7d0a9aa2a509',
    messagingSenderId: '159757857452',
    projectId: 'vnjob-1279d',
    storageBucket: 'vnjob-1279d.appspot.com',
    iosBundleId: 'com.example.myjobapp.RunnerTests',
  );
}
